<?php
declare(strict_types=1);
/**
 * The assignto view of task of ZenTaoPMS.
 */

/*
  ======= Attention ======

  This file is generated by zin-tool, you should check the following to-do list.

  + Familiar with the use of these widgets in zin: .
  + Check the following variables which used in widgets: $assignedToOptions.
  + Check the origin code in module/task/view/assignto.html.php, and ensure that all features have been implemented.
  + Check the origin js code in module/task/js/common.js and module/task/js/assignto.js
  + Check the origin css code in module/task/css/common.css and module/task/css/assignto.css
  + Remove the comments which starts with "zin:"
  + Test according to the new design draft and the original implementation
 */

namespace zin;

/* ====== Preparing and processing page data ====== */

/* zin: Set variables to define picker options for form */
$formTitle         = $task->name;
$assignedToOptions = $members;


/* ====== Define the page structure with zin widgets ====== */

/* zin: Define the form in main content */
formPanel
(
    set::title($formTitle), // The form title is diffrent from the page title,
    formGroup
    (
        set::width("1/3"),
        set::name("assignedTo"),
        set::label("指派"),
        set::value((empty($task->team) or strpos('done,cencel,closed', $task->status) !== false) ? $task->assignedTo : $task->nextUser),
        set::control("picker"),
        set::items($assignedToOptions)
    ),
    formGroup
    (
        set::width("1/3"),
        set::label("预计剩余"),
        inputGroup
        (
            control(set(array
            (
                'name' => "left",
                'id' => "left",
                'value' => $task->left,
                'disabled' => false,
                'type' => "text"
            ))),
            "小时"
        )
    ),
    formGroup
    (
        set::width("2/3"),
        set::name("comment"),
        set::label("备注"),
        set::control("editor")
    )
);


/* ====== Render page ====== */

render();
