sonar.projectKey=sunguangming:zentaopms
sonar.sources=.
sonar.language=php
sonar.branch.name=release/22.0
sonar.inclusions=lib/zin/wg/storybasicinfo/v1.php,module/story/model.php
sonar.working.directory=/tmp
sonar.exclusions=**/extension/**/ext/**,**/*.bak,**/*.sql,**/*.js,**/*.css,**/*.yaml,**/*.zip,**/*.out,**/lang/*,doc/*,**/test/**
