<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//FR"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
   <html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <!-- Generated by phpDocumentor on {$date}  -->
  <title>{$title}</title>
  <meta http-equiv='Content-Type' content='text/html; charset=gbk'/>
</head>

<FRAMESET rows='20,*'>
  <FRAME src='packages.html' name='left_top' frameborder="no" border="1" framespacing="0">
  <FRAMESET cols='200,*'>
    <FRAME src='{$start}' name='left_bottom' frameborder="no" border="1" framespacing="0">
    <FRAME src='{$blank}.html' name='right' frameborder="no" border="1" framespacing="0">
  </FRAMESET>
  <NOFRAMES>
    <H2>Frame Alert</H2>
    <P>This document is designed to be viewed using the frames feature.
    If you see this message, you are using a non-frame-capable web client.</P>
  </NOFRAMES>
</FRAMESET>
</HTML>
