<?php
$config->company = new stdclass();
$config->company->create = new stdclass();
$config->company->edit   = new stdclass();
$config->company->create->requiredFields = 'name,pms';
$config->company->edit->requiredFields   = 'name,pms';

global $lang, $app;
$app->loadLang('action');
$app->loadLang('user');
$config->company->dynamic = new stdclass();
$config->company->dynamic->search['module']               = 'action';
$config->company->dynamic->search['fields']['product']    = $lang->action->product;
$config->company->dynamic->search['fields']['actor']      = $lang->action->actor;
$config->company->dynamic->search['fields']['objectID']   = $lang->action->objectID;
$config->company->dynamic->search['fields']['project']    = $lang->action->project;
$config->company->dynamic->search['fields']['objectType'] = $lang->action->objectType;
$config->company->dynamic->search['fields']['date']       = $lang->action->date;
$config->company->dynamic->search['fields']['action']     = $lang->action->action;

$config->company->dynamic->search['params']['product']    = array('operator' => '=',  'control' => 'select', 'values' => '');
$config->company->dynamic->search['params']['actor']      = array('operator' => '=',  'control' => 'select', 'values' => '');
$config->company->dynamic->search['params']['objectID']   = array('operator' => '=',  'control' => 'input',  'values' => '');
$config->company->dynamic->search['params']['project']    = array('operator' => '=',  'control' => 'select', 'values' => '');
$config->company->dynamic->search['params']['objectType'] = array('operator' => '=',  'control' => 'select', 'values' => $lang->action->search->objectTypeList);
$config->company->dynamic->search['params']['date']       = array('operator' => '>=', 'control' => 'input',  'values' => '');
$config->company->dynamic->search['params']['action']     = array('operator' => '=',  'control' => 'select', 'values' => $lang->action->search->label);

$config->company->browse = new stdClass();
$config->company->browse->search['module']             = 'user';
$config->company->browse->search['fields']['realname'] = $lang->user->realname;
$config->company->browse->search['fields']['email']    = $lang->user->email;
$config->company->browse->search['fields']['dept']     = $lang->user->dept;
$config->company->browse->search['fields']['account']  = $lang->user->account;
$config->company->browse->search['fields']['role']     = $lang->user->role;
$config->company->browse->search['fields']['phone']    = $lang->user->phone;
$config->company->browse->search['fields']['join']     = $lang->user->join;
$config->company->browse->search['fields']['id']       = $lang->user->id;
$config->company->browse->search['fields']['commiter'] = $lang->user->commiter;
$config->company->browse->search['fields']['birthday'] = $lang->user->birthyear;
$config->company->browse->search['fields']['gender']   = $lang->user->gender;
$config->company->browse->search['fields']['qq']       = $lang->user->qq;
$config->company->browse->search['fields']['msn']      = $lang->user->msn;
$config->company->browse->search['fields']['yahoo']    = $lang->user->yahoo;
$config->company->browse->search['fields']['gtalk']    = $lang->user->gtalk;
$config->company->browse->search['fields']['wangwang'] = $lang->user->wangwang;
$config->company->browse->search['fields']['address']  = $lang->user->address;
$config->company->browse->search['fields']['zipcode']  = $lang->user->zipcode;

$config->company->browse->search['params']['realname'] = array('operator' => 'include',  'control' => 'input',  'values' => '');
$config->company->browse->search['params']['email']    = array('operator' => 'include',  'control' => 'input',  'values' => '');
$config->company->browse->search['params']['dept']     = array('operator' => 'belong',   'control' => 'select', 'values' => '');
$config->company->browse->search['params']['account']  = array('operator' => 'include',  'control' => 'input',  'values' => '');
$config->company->browse->search['params']['role']     = array('operator' => '=',        'control' => 'select', 'values' => $lang->user->roleList);
$config->company->browse->search['params']['phone']    = array('operator' => 'include',  'control' => 'input',  'values' => '');
$config->company->browse->search['params']['join']     = array('operator' => '>=',       'control' => 'input',  'values' => '', 'class' => 'date');
$config->company->browse->search['params']['id']       = array('operator' => '=',        'control' => 'input',  'values' => '');
$config->company->browse->search['params']['commiter'] = array('operator' => 'include',  'control' => 'select', 'values' => '');
$config->company->browse->search['params']['birthday'] = array('operator' => '>=',       'control' => 'input',  'values' => '', 'class' => 'date');
$config->company->browse->search['params']['gender']   = array('operator' => '=',        'control' => 'select', 'values' => $lang->user->genderList);
$config->company->browse->search['params']['qq']       = array('operator' => '=',        'control' => 'input',  'values' => '');
$config->company->browse->search['params']['msn']      = array('operator' => '=',        'control' => 'input',  'values' => '');
$config->company->browse->search['params']['yahoo']    = array('operator' => '=',        'control' => 'input',  'values' => '');
$config->company->browse->search['params']['gtalk']    = array('operator' => '=',        'control' => 'input',  'values' => '');
$config->company->browse->search['params']['wangwang'] = array('operator' => '=',        'control' => 'input',  'values' => '');
$config->company->browse->search['params']['address']  = array('operator' => 'include',  'control' => 'input',  'values' => '');
$config->company->browse->search['params']['zipcode']  = array('operator' => '=',        'control' => 'input',  'values' => '');
