<?php
$now   = helper::now();
$today = helper::today();

global $app, $lang;
$config->story->form = new stdclass();
$config->story->form->create = array();
$config->story->form->create['product']     = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['branch']      = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['module']      = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['plan']        = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['assignedTo']  = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => '', 'options' => 'users');
$config->story->form->create['source']      = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => '', 'options' => $lang->story->sourceList);
$config->story->form->create['sourceNote']  = array('type' => 'string',  'control' => 'text',         'required' => false, 'default' => '', 'filter'  => 'trim');
$config->story->form->create['feedbackBy']  = array('type' => 'string',  'control' => 'text',         'required' => false, 'default' => '', 'filter'  => 'trim');
$config->story->form->create['notifyEmail'] = array('type' => 'string',  'control' => 'text',         'required' => false, 'default' => '', 'filter'  => 'trim');
$config->story->form->create['reviewer']    = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'options' => 'users');
$config->story->form->create['URS']         = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'options' => array());
$config->story->form->create['parent']      = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['region']      = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['lane']        = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->story->form->create['title']       = array('type' => 'string',  'control' => 'text',         'required' => true,  'filter'  => 'trim');
$config->story->form->create['color']       = array('type' => 'string',  'control' => 'color',        'required' => false, 'default' => '');
$config->story->form->create['category']    = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => 'feature', 'options' => $lang->story->categoryList);
$config->story->form->create['pri']         = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => $config->story->defaultPriority, 'options' => array_filter($lang->story->priList));
$config->story->form->create['estimate']    = array('type' => 'float',   'control' => 'text',         'required' => false, 'default' => 0);
$config->story->form->create['spec']        = array('type' => 'string',  'control' => 'editor',       'required' => false, 'default' => '');
$config->story->form->create['verify']      = array('type' => 'string',  'control' => 'editor',       'required' => false, 'default' => '');
$config->story->form->create['keywords']    = array('type' => 'string',  'control' => 'text',         'required' => false, 'default' => '');
$config->story->form->create['type']        = array('type' => 'string',  'control' => 'hidden',       'required' => false, 'default' => 'story',);
$config->story->form->create['mailto']      = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'filter' => 'join', 'options' => 'users');
$config->story->form->create['status']      = array('type' => 'string',  'control' => 'hidden',       'required' => false, 'default' => 'active');
$config->story->form->create['branches']    = array('type' => 'array',   'control' => 'select',       'required' => false, 'default' => 0, 'options' => array());
$config->story->form->create['modules']     = array('type' => 'array',   'control' => 'select',       'required' => false, 'default' => 0, 'options' => array());
$config->story->form->create['plans']       = array('type' => 'array',   'control' => 'select',       'required' => false, 'default' => 0, 'options' => array());
$config->story->form->create['vision']      = array('type' => 'string',  'control' => '',             'required' => false, 'default' => $config->vision);
$config->story->form->create['version']     = array('type' => 'int',     'control' => '',             'required' => false, 'default' => 1);
$config->story->form->create['openedBy']    = array('type' => 'string',  'control' => '',             'required' => false, 'default' => $app->user->account);
$config->story->form->create['openedDate']  = array('type' => 'string',  'control' => '',             'required' => false, 'default' => helper::now());

$app->loadLang('kanban');
$config->story->form->batchCreate = common::formConfig('story', 'batchCreate');
$config->story->form->batchCreate['branch']     = array('label' => $lang->story->branch,     'ditto' => true,  'type' => 'int',    'control' => 'select',   'required' => false, 'default' => 0,  'options' => array());
$config->story->form->batchCreate['module']     = array('label' => $lang->story->module,     'ditto' => true,  'type' => 'int',    'control' => 'select',   'required' => false, 'default' => 0,  'options' => array());
$config->story->form->batchCreate['plan']       = array('label' => $lang->story->plan,       'ditto' => true,  'type' => 'int',    'control' => 'select',   'required' => false, 'default' => 0,  'options' => array());
$config->story->form->batchCreate['assignedTo'] = array('label' => $lang->story->assignedTo, 'ditto' => false, 'type' => 'string', 'control' => 'select',   'required' => false, 'default' => '', 'options' => 'users');
$config->story->form->batchCreate['region']     = array('label' => $lang->kanbancard->region,'ditto' => false, 'type' => 'int',    'control' => 'select',   'required' => false, 'default' => 0,  'options' => array());
$config->story->form->batchCreate['lane']       = array('label' => $lang->kanbancard->lane,  'ditto' => false, 'type' => 'int',    'control' => 'select',   'required' => false, 'default' => 0,  'options' => array());
$config->story->form->batchCreate['title']      = array('label' => $lang->story->title,      'ditto' => false, 'type' => 'string', 'control' => 'text',     'required' => true,  'default' => '', 'filter'  => 'trim', 'base' => true);
$config->story->form->batchCreate['spec']       = array('label' => $lang->story->spec,       'ditto' => false, 'type' => 'string', 'control' => 'textarea', 'required' => false, 'default' => '');
$config->story->form->batchCreate['source']     = array('label' => $lang->story->source,     'ditto' => true,  'type' => 'string', 'control' => 'select',   'required' => false, 'default' => '', 'options' => $lang->story->sourceList);
$config->story->form->batchCreate['sourceNote'] = array('label' => $lang->story->sourceNote, 'ditto' => false, 'type' => 'string', 'control' => 'text',     'required' => false, 'default' => '', 'filter'  => 'trim');
$config->story->form->batchCreate['verify']     = array('label' => $lang->story->verify,     'ditto' => false, 'type' => 'string', 'control' => 'textarea', 'required' => false, 'default' => '');
$config->story->form->batchCreate['category']   = array('label' => $lang->story->category,   'ditto' => true,  'type' => 'string', 'control' => 'select',   'required' => false, 'default' => 'feature', 'options' => $lang->story->categoryList);
$config->story->form->batchCreate['pri']        = array('label' => $lang->story->pri,        'ditto' => false, 'type' => 'int',    'control' => 'select',   'required' => false, 'default' => $config->story->defaultPriority, 'options' => $lang->story->priList);
$config->story->form->batchCreate['estimate']   = array('label' => $lang->story->estimate,   'ditto' => false, 'type' => 'float',  'control' => 'text',     'required' => false, 'default' => 0);
$config->story->form->batchCreate['reviewer']   = array('label' => $lang->story->reviewedBy, 'ditto' => true,  'type' => 'array',  'control' => 'select',   'required' => false, 'default' => '', 'multiple' => true, 'options' => array());
$config->story->form->batchCreate['URS']        = array('label' => $lang->story->URS,        'ditto' => false, 'type' => 'array',  'control' => 'select',   'required' => false, 'default' => '', 'multiple' => true);
$config->story->form->batchCreate['parent']     = array('label' => $lang->story->parent,     'ditto' => false, 'type' => 'int',    'control' => 'select',   'required' => false, 'default' => '');
$config->story->form->batchCreate['keywords']   = array('label' => $lang->story->keywords,   'ditto' => false, 'type' => 'string', 'control' => 'text',     'required' => false, 'default' => '');
$config->story->form->batchCreate['mailto']     = array('label' => $lang->story->mailto,     'ditto' => false, 'type' => 'array',  'control' => 'select',   'required' => false, 'default' => '', 'multiple' => true, 'options' => 'users', 'filter' => 'join');

$config->story->form->batchEdit = array();
$config->story->form->batchEdit['branch']       = array('type' => 'int',    'width' => '200px', 'control' => 'select', 'required' => false, 'default' => 0, 'options' => array());
$config->story->form->batchEdit['module']       = array('type' => 'int',    'width' => '200px', 'control' => 'select', 'required' => false, 'default' => 0, 'options' => array());
$config->story->form->batchEdit['plan']         = array('type' => 'int',    'width' => '200px', 'control' => 'select', 'required' => false, 'default' => 0, 'options' => array());
$config->story->form->batchEdit['title']        = array('type' => 'string', 'width' => '240px', 'control' => 'text',   'required' => true,  'filter'  => 'trim', 'base' => true);
$config->story->form->batchEdit['estimate']     = array('type' => 'float',  'width' => '76px',  'control' => 'text',   'required' => false, 'default' => '0');
$config->story->form->batchEdit['category']     = array('type' => 'string', 'width' => '160px', 'control' => 'select', 'required' => false, 'default' => 'feature', 'options' => array_filter($lang->story->categoryList));
$config->story->form->batchEdit['pri']          = array('type' => 'string', 'width' => '92px',  'control' => 'select', 'required' => false, 'default' => $config->story->defaultPriority,  'options' => array_filter($lang->story->priList));
$config->story->form->batchEdit['assignedTo']   = array('type' => 'string', 'width' => '136px', 'control' => 'select', 'required' => false, 'default' => '', 'options' => 'users');
$config->story->form->batchEdit['source']       = array('type' => 'string', 'width' => '160px', 'control' => 'select', 'required' => false, 'default' => '', 'options' => array_filter($lang->story->sourceList));
$config->story->form->batchEdit['sourceNote']   = array('type' => 'string', 'width' => '200px', 'control' => 'text',   'required' => false, 'default' => '', 'filter'  => 'trim');
$config->story->form->batchEdit['status']       = array('type' => 'string', 'width' => '80px',  'control' => 'static', 'required' => false, 'default' => 0,  'options' => array_filter($lang->story->statusList));
$config->story->form->batchEdit['stage']        = array('type' => 'string', 'width' => '120px', 'control' => 'select', 'required' => false, 'default' => 0,  'options' => array_filter($lang->story->stageList));
$config->story->form->batchEdit['closedBy']     = array('type' => 'string', 'width' => '136px', 'control' => 'select', 'required' => false, 'default' => '', 'options' => 'users');
$config->story->form->batchEdit['closedReason'] = array('type' => 'string', 'width' => '80px',  'control' => 'select', 'required' => false, 'default' => '', 'options' => array_filter($lang->story->reasonList));
$config->story->form->batchEdit['keywords']     = array('type' => 'string', 'width' => '200px', 'control' => 'text',   'required' => false, 'default' => '', 'filter'  => 'trim');

$config->story->form->batchClose = array();
$config->story->form->batchClose['title']        = array('type' => 'string', 'width' => '300px', 'control' => 'text',   'required' => false, 'filter'  => 'trim', 'base' => true);
$config->story->form->batchClose['status']       = array('type' => 'string', 'width' => '90px',  'control' => 'select', 'required' => false, 'default' => 0,  'options' => array_filter($lang->story->statusList));
$config->story->form->batchClose['closedReason'] = array('type' => 'string', 'width' => '300px', 'control' => 'select', 'required' => true,  'default' => '');
$config->story->form->batchClose['comment']      = array('type' => 'string', 'control' => 'text', 'required' => false, 'default' => '', 'filter' => 'trim');

$config->story->form->change = array();
$config->story->form->change['reviewer']       = array('type' => 'array',   'control' => 'multi-select', 'required' => true,  'default' => '', 'filter' => 'join', 'options' => '');
$config->story->form->change['title']          = array('type' => 'string',  'control' => 'text',         'required' => true,  'filter'  => 'trim');
$config->story->form->change['color']          = array('type' => 'string',  'control' => 'color',        'required' => false, 'default' => '');
$config->story->form->change['spec']           = array('type' => 'string',  'control' => 'editor',       'required' => false, 'default' => '');
$config->story->form->change['verify']         = array('type' => 'string',  'control' => 'editor',       'required' => false, 'default' => '');
$config->story->form->change['status']         = array('type' => 'string',  'control' => 'hidden',       'required' => false, 'default' => '');
$config->story->form->change['lastEditedDate'] = array('type' => 'string',  'control' => 'hidden',       'required' => false, 'default' => '');

$config->story->form->review = array();
$config->story->form->review['reviewedDate']   = array('type' => 'date',    'control' => 'text',   'required' => false, 'default' => '');
$config->story->form->review['result']         = array('type' => 'string',  'control' => 'select', 'required' => true,  'default' => '', 'options' => '', 'title' => $lang->story->reviewResult);
$config->story->form->review['assignedTo']     = array('type' => 'string',  'control' => 'select', 'required' => false, 'default' => '', 'options' => 'users');
$config->story->form->review['closedReason']   = array('type' => 'string',  'control' => 'select', 'required' => false, 'default' => '', 'options' => $lang->story->reasonList, 'title' => $lang->story->rejectedReason);
$config->story->form->review['pri']            = array('type' => 'int',     'control' => 'select', 'required' => false, 'default' => '', 'options' => $lang->story->priList);
$config->story->form->review['estimate']       = array('type' => 'float',   'control' => 'text',   'required' => false, 'default' => '');
$config->story->form->review['duplicateStory'] = array('type' => 'string',  'control' => 'text',   'required' => false, 'default' => '');
$config->story->form->review['childStories']   = array('type' => 'string',  'control' => 'text',   'required' => false, 'default' => '');
$config->story->form->review['status']         = array('type' => 'string',  'control' => 'hidden', 'required' => false, 'default' => '');

$config->story->form->activate = array();
$config->story->form->activate['assignedTo']     = array('type' => 'string',   'required' => false, 'default' => '');
$config->story->form->activate['activatedDate']  = array('type' => 'datetime', 'required' => false, 'default' => $now);
$config->story->form->activate['lastEditedDate'] = array('type' => 'datetime', 'required' => false, 'default' => $now);
$config->story->form->activate['lastEditedBy']   = array('type' => 'string',   'required' => false, 'default' => $app->user->account);
$config->story->form->activate['closedBy']       = array('type' => 'string',   'required' => false, 'default' => '');
$config->story->form->activate['closedReason']   = array('type' => 'string',   'required' => false, 'default' => '');
$config->story->form->activate['closedDate']     = array('type' => 'datetime', 'required' => false, 'default' => null);
$config->story->form->activate['reviewedBy']     = array('type' => 'string',   'required' => false, 'default' => '');
$config->story->form->activate['reviewedDate']   = array('type' => 'datetime', 'required' => false, 'default' => null);
$config->story->form->activate['assignedDate']   = array('type' => 'datetime', 'required' => false, 'default' => $now);
$config->story->form->activate['duplicateStory'] = array('type' => 'int',      'required' => false, 'default' => 0);
$config->story->form->activate['childStories']   = array('type' => 'string',   'required' => false, 'default' => '');
