<?php
$config->ai->initAIPrompts = array();
$config->ai->initAIPrompts[] = (object)['id' => 1, 'code' => 'zt_create_doc',      'name' => '编写开发设计文档智能体', 'model' => 0, 'desc' => '根据任务的名称、描述、设计类型、后端框架、前端框架和数据库类型等信息生成一篇开发设计文档。', 'module' => 'task', 'source' => ',task.name,task.desc,task.pri,task.status,task.estimate,task.consumed,task.left,task.progress,task.estStarted,task.realStarted,task.story,', 'targetForm' => 'doc.create', 'purpose' => '请根据任务数据、 <设计类型> 、 <后端框架> 、 <前端框架>  和 <数据库类型>  生成一篇开发设计文档。', 'elaboration' => '', 'role' => '你是一名经验丰富的开发工程师。', 'characterization' => '精通多种编程语言和框架、熟悉前后端技术和架构、擅长性能优化和安全防护、熟悉云计算和容器化技术、能够协调多人协作和项目管理。', 'status' => 'active', 'createdBy' => 'system'];
$config->ai->initAIPrompts[] = (object)['id' => 2, 'code' => 'zt_story_prototype', 'name' => '绘制需求原型图智能体',   'model' => 0, 'desc' => '根据输入的需求信息, 生成一个HTML格式的原型图示例。', 'module' => 'story', 'source' => ',story.title,story.spec,story.verify,story.product,story.module,story.pri,story.category,story.estimate,', 'targetForm' => 'empty.empty', 'purpose' => '根据输入的需求信息，生成一个HTML格式的原型图示例。原型图应包含以下部分：\n1. 标题\n2. 整体结构框架（如导航栏、侧边栏、主要内容区）\n3. 各功能模块的简要设计（如按钮、表单、图表等）\n4. 交互设计提示（如如何进行用户操作）\n5. 请生成完整的 HTML5 页面代码，包括开始的 `&lt;!DOCTYPE html&gt;` 和 结束的 `&lt;/html&gt;`，使用 markdown html 代码块表示，如果有多个页面请使用多个代码块表示。\n6. 如果页面有 CSS，应该直接在 HTML 页面内使用内联样式 `&lt;style&gt;`表示，而不是链接单独的 CSS 文件。',
'elaboration' => '', 'role' => '请你扮演一名资深的产品经理。', 'characterization' => '负责绘制需求原型图的过程。您将需求转化为可视化的原型图，同时确保其符合需求描述和需求验收标准。', 'status' => 'active', 'createdBy' => 'system'];

$config->ai->initAIPrompts[] = (object)['id' => 3, 'code' => 'zt_release_newsletter', 'name' => '编写发布新闻稿', 'model' => 0, 'desc' => '根据发布详情信息、需求列表和Bug列表生成符合模板规范的新闻稿。', 'module' => 'release', 'source' => ',release.product,release.name,release.desc,release.date,stories.title,stories.estimate,bugs.title,', 'targetForm' => 'doc.create', 'purpose' => '请根据发布信息以及发布中关联的需求和Bug编写发布新闻稿。\n要求： 1.新闻稿格式严格参考产品**新闻稿通用模板**：\n#### **新闻标题** **\\[产品名称\\] \\[版本号\\] 正式发布，新增\\[亮点功能\\]！**\n#### **新闻导语** 大家好， 我们很高兴地宣布，**\\[产品名称\\] \\[版本号\\] 正式发布！** **本次发布新增了\\[核心功能名称\\]!** 该功能支持\\[简要功能描述\\]，帮助用户\\[解决什么问题\\]，提升\\[具体价值\\]。 同时，我们优化了\\[其他方面\\]，安装更简单，修复了已知Bug。\n#### **新增功能亮点**\n**本版本主要新增功能包括：**\n- **\\[功能模块1\\]**：\\[具体功能点\\]\n- **\\[功能模块2\\]**：\\[具体功能点\\]\n- **\\[优化改进\\]**：\\[具体优化点\\]\n#### **功能详细说明**\n- **跨\\[产品/项目\\]协作**\n- 支持\\[具体应用场景\\]\n- 解决\\[用户痛点\\]\n- **安装与部署优化**\n- 安装向导简化\n- 解压/安装速度提升\n- **界面与体验改进**\n- 用户界面升级\n- 操作流程优化\n#### **下载与安装** 我们提供多种安装方式：\n- **Windows版** - \\[安装版下载\\]\n- \\[免安装版下载\\] - **Linux版**\n- \\[安装版下载\\]\n- \\[免安装版下载\\]\n- **源码版** - \\[PHP 7.x版\\]\n- \\[PHP 8.x版\\]\n- **Docker镜像**\n- \\[Docker Hub地址\\]\n#### **文档支持** - 安装指南：\\[链接\\] - 升级指南：\\[链接\\] - 使用手册：\\[链接\\] - 常见问题解答：\\[链接\\]\n#### **结语** 新版本将为用户带来更好的使用体验和更高的工作效率，感谢大家一直以来的支持与反馈！我们将继续努力，提供更优秀的产品和服务！ 2.新闻稿通用模板中的功能亮点需要对需求列表中的需求进行总结，在功能详细说明里面描述清楚。\n3.将markdown格式渲染出来',
'elaboration' => '', 'role' => '请你扮演一名资深的产品经理。', 'characterization' => '负责产品战略、设计、开发、数据分析、用户体验、团队管理、沟通协调等方面，需要具备多种技能和能力，以实现产品目标和公司战略。', 'status' => 'active', 'createdBy' => 'system'];

$config->ai->initAIPrompts[] = (object)['id' => 4, 'code' => 'zt_project_proposal', 'name' => '编写立项报告', 'model' => 0, 'desc' => '根据项目基本信息、阶段或迭代信息生成项目立项报告。', 'module' => 'project', 'source' => ',project.name,project.type,project.desc,project.begin,project.end,project.estimate,programplans.name,programplans.desc,programplans.status,programplans.begin,programplans.end,programplans.realBegan,programplans.realEnd,programplans.progress,programplans.estimate,programplans.consumed,programplans.left,executions.name,executions.desc,executions.status,executions.begin,executions.end,executions.realBegan,executions.realEnd,executions.estimate,executions.consumed,executions.progress,', 'targetForm' => 'doc.create', 'purpose' => '请根据项目信息、阶段或迭代信息生成一份项目立项报告。\n要求： 1.严格参考项目立项报告模板：\n## 一、项目基本信息\n| 项目名称 | 项目代号 | 所属部门 | 项目负责人 | 开始日期 | 结束日期 | 预计周期 | 项目类型 | 项目阶段 |\n|----------|----------|----------|------------|----------|----------|-----------|-----------|-----------|\n| | | | | | | | | |\n## 二、项目背景与立项目的\n### 1. 项目背景 简要说明项目产生的背景、市场或业务需求，以及项目的必要性。\n### 2. 立项目的 明确项目的目标，以及希望通过本项目实现的战略或业务目标。\n## 三、项目目标与关键指标（OKR）\n| 目标 | 关键结果（KR） | 责任人 | 完成时间 |\n|------|----------------|--------|----------|\n| | | | | | | | | |\n## 四、项目范围与内容\n### 1. 项目范围 简要说明本项目的开发范围，包括产品功能、技术实现、市场定位等。\n### 2. 主要功能/产品特性 列出产品的核心功能或主要特性，说明其市场价值与竞争优势。\n### 3. 目标用户群 明确产品的目标用户群体，包括年龄、性别、使用场景等信息。\n## 五、市场与竞争分析\n### 1. 市场需求 分析当前市场对本产品的需求情况，包括市场规模、增长率、用户痛点等。\n### 2. 竞争分析 简述主要竞争对手的产品情况、市场占有率、优势与劣势。\n### 3. 项目差异化优势 说明本项目相较于竞品的差异化优势。\n## 六、项目资源计划\n### 1. 人力资源 列出主要项目成员及分工，包括项目经理、研发人员、测试人员、市场人员等。\n### 2. 技术资源 说明所需的技术平台、开发工具、测试设备等资源。\n### 3. 资金预算 列出项目的总预算、分项支出及资金来源。\n## 七、项目实施计划（甘特图或阶段划分）\n### 1. 项目阶段划分 将项目划分为几个主要阶段，并简要说明每个阶段的目标和交付物。\n## 八、风险评估与应对策略\n| 风险 | 影响 | 可能性 | 应对措施 |\n|------|------|--------|----------|\n## 九、项目收益与预期成果\n### 1. 项目收益 说明项目成功后的预期收益，包括财务、市场、品牌等层面。\n### 2. 项目成果 列出项目完成后的主要成果，包括产品、文档、知识产权等。',
'elaboration' => '', 'role' => '请你扮演一名经验丰富的项目经理。', 'characterization' => '具备项目计划制定、进度管理、成本控制、团队管理、沟通协调、风险管理、质量控制、敏捷开发、互联网技术和数据分析等多方面的技能和能力。', 'status' => 'active', 'createdBy' => 'system'];

$config->ai->initAIPrompts[] = (object)['id' => 5, 'code' => 'zt_project_finalreport', 'name' => '编写结项报告', 'model' => 0, 'desc' => '根据项目基本信息、阶段或迭代信息生成项目结项报告。', 'module' => 'project', 'source' => ',project.name,project.type,project.desc,project.begin,project.end,project.estimate,programplans.name,programplans.desc,programplans.status,programplans.begin,programplans.end,programplans.realBegan,programplans.realEnd,programplans.progress,programplans.estimate,programplans.consumed,programplans.left,executions.name,executions.desc,executions.status,executions.begin,executions.end,executions.realBegan,executions.realEnd,executions.estimate,executions.consumed,executions.progress,', 'targetForm' => 'doc.create', 'purpose' => '请根据项目信息、阶段或迭代信息生成一份项目结项报告。\n要求： 1.严格参考项目结项报告模板：\n## 一、项目基本信息\n| 项目名称 | 项目代号 | 所属部门 | 项目负责人 | 项目周期 | 开始日期 | 结束日期 | 项目类型 | 项目阶段 |\n|----------|----------|----------|------------|----------|----------|----------|-----------|-----------|\n|          |          |          |            |          |          |          |           |           |\n## 二、项目概况\n### 1. 项目背景\n简要回顾项目立项时的背景、目标及意义。\n### 2. 项目目标\n总结项目初期设定的目标及关键绩效指标（KPI）。\n## 三、项目实施过程\n### 1. 项目阶段回顾\n按照项目阶段划分，简要说明各阶段的完成情况。\n### 2. 关键里程碑\n列出项目中的关键里程碑及完成时间。\n## 四、项目成果与交付物\n### 1. 项目成果\n列出项目完成后的主要成果。\n### 2. 项目交付物\n列出项目交付的成果物。\n> 示例：\n| 交付物 | 类型 | 状态 |\n|--------|------|------|\n| 需求文档 | 文档类 | 已完成 |\n| 系统设计文档 | 文档类 | 已完成 |\n| 产品原型 | 硬件/软件 | 已交付 |\n| 测试报告 | 文档类 | 已完成 |\n| 用户手册 | 文档类 | 已完成 |\n## 五、项目质量与测试\n### 1. 质量管理\n简要说明项目中采用的质量管理方法与工具。\n> 示例：采用ISO 9001质量管理体系，结合敏捷开发与测试驱动开发（TDD）进行质量控制。\n### 2. 测试结果\n列出关键测试的执行情况及结果。\n## 六、项目成本与预算执行情况\n## 七、项目风险与问题回顾\n### 1. 风险回顾\n总结项目实施过程中出现的风险及应对措施。\n### 2. 项目问题及处理\n列出项目中遇到的问题及其解决方案。\n## 八、项目收益与价值\n### 1. 项目收益\n说明项目完成后的实际收益，包括财务、市场、品牌等方面。\n### 2. 项目价值\n总结项目对团队、公司及行业的价值。\n## 九、项目经验与教训\n### 1. 成功经验\n总结项目实施过程中的成功做法与经验。\n### 2. 存在问题\n总结项目中存在的问题及改进建议。',
'elaboration' => '', 'role' => '请你扮演一名经验丰富的项目经理。', 'characterization' => '具备项目计划制定、进度管理、成本控制、团队管理、沟通协调、风险管理、质量控制、敏捷开发、互联网技术和数据分析等多方面的技能和能力。', 'status' => 'active', 'createdBy' => 'system'];

$config->ai->initAIPrompts[] = (object)['id' => 6, 'code' => 'zt_automatic_test', 'name' => '编写自动化测试脚本', 'model' => 0, 'desc' => '根据用例的基本信息、步骤描述、预期结果和补充信息生成自动化测试脚本。', 'module' => 'case', 'source' => ',case.title,case.precondition,case.scene,case.product,case.module,case.pri,case.type,case.lastRunResult,case.status,steps.desc,steps.expect,', 'targetForm' => 'empty.empty', 'purpose' => '请根据用例信息、 <系统类型> <后端框架> <前端框架> <测试类型> 和 <其他信息> 生成自动化测试脚本。', 'elaboration' => '', 'role' => '作为一名资深的测试工程师。', 'characterization' => '测试工程师应该是专业且严谨的。熟悉测试流程和方法，精通自动化测试和性能测试，能够设计和编写测试用例和测试脚本，擅长问题诊断和分析，熟悉敏捷开发和持续集成，能够协调多部门合作和项目管理。', 'status' => 'active', 'createdBy' => 'system'];

$config->ai->initAIPromptFields = array();
$config->ai->initAIPromptFields[1][] = (object)['name' => '设计类型',   'type' => 'radio', 'placeholder' => '', 'options' => '系统设计,架构设计,接口设计,数据库设计', 'required' => 0];
$config->ai->initAIPromptFields[1][] = (object)['name' => '后端框架',   'type' => 'radio', 'placeholder' => '', 'options' => 'PHP,Go,Java,Python,Node.js,其他', 'required' => 0];
$config->ai->initAIPromptFields[1][] = (object)['name' => '前端框架',   'type' => 'radio', 'placeholder' => '', 'options' => 'JavaScript,Vue,React,Angular,其他', 'required' => 0];
$config->ai->initAIPromptFields[1][] = (object)['name' => '数据库类型', 'type' => 'radio', 'placeholder' => '', 'options' => 'MySQL,PostgreSQL,Oracle Database,Microsoft SQL Server,非关系型数据库', 'required' => 0];

$config->ai->initAIPromptFields[4][] = (object)['name' => '潜在风险', 'type' => 'textarea', 'placeholder' => '', 'required' => 0];
$config->ai->initAIPromptFields[4][] = (object)['name' => '预期收益', 'type' => 'textarea', 'placeholder' => '', 'required' => 0];

$config->ai->initAIPromptFields[6][] = (object)['name' => '系统类型', 'type' => 'checkbox', 'placeholder' => '', 'options' => 'Web,APP,API',                       'required' => 1];
$config->ai->initAIPromptFields[6][] = (object)['name' => '后端框架', 'type' => 'radio',    'placeholder' => '', 'options' => 'PHP,Go,Java,Python,Node.js,其他',   'required' => 1];
$config->ai->initAIPromptFields[6][] = (object)['name' => '前端框架', 'type' => 'radio',    'placeholder' => '', 'options' => 'JavaScript,Vue,React,Angular,其他', 'required' => 1];
$config->ai->initAIPromptFields[6][] = (object)['name' => '测试类型', 'type' => 'radio',    'placeholder' => '', 'options' => '单元测试,接口测试,UI测试',          'required' => 1];
$config->ai->initAIPromptFields[6][] = (object)['name' => '其他信息', 'type' => 'textarea', 'placeholder' => '', 'required' => 0];
