<?php
namespace zin;

formPanel
(
    set::title($lang->deliverable->create),
    set::grid(true),
    set::layout('grid'),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->deliverable->name),
        set::name('name')
    ),
    formGroup(set::width('1/2')),
    formGroup
    (
        set::width('1/3'),
        set::label($lang->deliverable->module),
        picker
        (
            set::name('module'),
            set::items(array())
        )
    ),
    formGroup
    (
        set::width('1/6'),
        set::label($lang->deliverable->method),
        picker
        (
            set::name('method'),
            set::items(array())
        )
    ),
    formGroup(set::width('1/2')),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->deliverable->model),
        picker
        (
            set::name('model'),
            set::multiple(true),
            set::items(array())
        )
    ),
    formGroup
    (
        set::width('full'),
        set::label($lang->deliverable->desc),
        editor
        (
            set::name('desc')
        )
    ),
    formGroup
    (
        setClass('template-group'),
        set::label($lang->deliverable->template),
        picker
        (
            set::name('template'),
            set::items(array())
        )
    ),
    formGroup
    (
        setClass('template-or'),
        set::label(''),
        inputGroup
        (
            $lang->deliverable->or
        )
    ),
    formGroup
    (
        setClass('template-group'),
        set::label($lang->deliverable->files),
        fileinput
        (
            set::name('files')
        )
    )
);
