ALTER TABLE `zt_project` 
ADD `template` char(30) NOT NULL AFTER `catID`,
ADD `category` varchar(20) COLLATE 'utf8_general_ci' NOT NULL DEFAULT 'single' AFTER `type`,
ADD `program` mediumint(8) NOT NULL DEFAULT '0' AFTER `category`,
ADD `budget` varchar(30) NOT NULL DEFAULT '0' AFTER `program`,
ADD `budgetUnit` char(30) NOT NULL  DEFAULT 'yuan' AFTER `budget`,
ADD `percent` float unsigned NOT NULL DEFAULT '0' AFTER `budgetUnit`,
ADD `privway` char(30) NOT NULL AFTER `percent`,
ADD `milestone` enum('0','1') NOT NULL default '0' AFTER `percent`,
ADD `attribute` varchar(30) NOT NULL DEFAULT '' AFTER `budgetUnit`,
ADD `realStarted` date NOT NULL AFTER `end`,
ADD `realFinished` date NOT NULL AFTER `realStarted`,
ADD `version` smallint(6) NOT NULL AFTER `desc`,
ADD `parentVersion` smallint(6) NOT NULL AFTER `version`,
ADD `planDuration` int(11) NOT NULL AFTER `parentVersion`,
ADD `realDuration` int(11) NOT NULL AFTER `planDuration`,
ADD `output` text NOT NULL AFTER `milestone`;

ALTER TABLE `zt_product` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_task` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_doc` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_story` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_repo` ADD `program` varchar(255) NOT NULL AFTER `id`;
ALTER TABLE `zt_bug` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_case` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_testtask` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_testreport` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_testsuite` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_build` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;
ALTER TABLE `zt_release` ADD `program` mediumint(8) unsigned NOT NULL AFTER `id`;

ALTER TABLE `zt_group` ADD `program` mediumint(8) NOT NULL DEFAULT '0' AFTER `id`;
INSERT INTO `zt_group` (`name`, `role`, `desc`) VALUES ('项目管理员', 'pgmadmin', '项目管理员可以维护项目的权限');

ALTER TABLE `zt_usergroup` ADD `program` text NOT NULL;

ALTER TABLE `zt_userview` ADD `programs` mediumtext COLLATE 'utf8_general_ci' NOT NULL AFTER `account`;

REPLACE INTO `zt_grouppriv` (`group`, `module`, `method`) VALUES
(1, 'my', 'program'),
(1, 'program', 'activate'),
(1, 'program', 'close'),
(1, 'program', 'create'),
(1, 'program', 'delete'),
(1, 'program', 'edit'),
(1, 'program', 'export'),
(1, 'program', 'finish'),
(1, 'program', 'index'),
(1, 'program', 'manageMembers'),
(1, 'program', 'setPlanduration'),
(1, 'program', 'start'),
(1, 'program', 'suspend'),
(1, 'program', 'transfer'),
(2, 'my', 'program'),
(2, 'program', 'activate'),
(2, 'program', 'close'),
(2, 'program', 'create'),
(2, 'program', 'delete'),
(2, 'program', 'edit'),
(2, 'program', 'finish'),
(2, 'program', 'index'),
(2, 'program', 'setPlanduration'),
(2, 'program', 'start'),
(2, 'program', 'suspend'),
(2, 'program', 'transfer'),
(3, 'my', 'program'),
(3, 'program', 'activate'),
(3, 'program', 'close'),
(3, 'program', 'create'),
(3, 'program', 'edit'),
(3, 'program', 'finish'),
(3, 'program', 'index'),
(3, 'program', 'setPlanduration'),
(3, 'program', 'start'),
(3, 'program', 'suspend'),
(3, 'program', 'transfer'),
(4, 'my', 'program'),
(4, 'program', 'activate'),
(4, 'program', 'close'),
(4, 'program', 'create'),
(4, 'program', 'delete'),
(4, 'program', 'edit'),
(4, 'program', 'finish'),
(4, 'program', 'index'),
(4, 'program', 'manageMembers'),
(4, 'program', 'setPlanduration'),
(4, 'program', 'start'),
(4, 'program', 'suspend'),
(4, 'program', 'transfer'),
(5, 'my', 'program'),
(5, 'program', 'activate'),
(5, 'program', 'close'),
(5, 'program', 'create'),
(5, 'program', 'delete'),
(5, 'program', 'edit'),
(5, 'program', 'finish'),
(5, 'program', 'index'),
(5, 'program', 'start'),
(5, 'program', 'suspend'),
(6, 'my', 'program'),
(6, 'program', 'activate'),
(6, 'program', 'close'),
(6, 'program', 'create'),
(6, 'program', 'delete'),
(6, 'program', 'edit'),
(6, 'program', 'finish'),
(6, 'program', 'index'),
(6, 'program', 'manageMembers'),
(6, 'program', 'setPlanduration'),
(6, 'program', 'start'),
(6, 'program', 'suspend'),
(6, 'program', 'transfer'),
(7, 'my', 'program'),
(7, 'program', 'activate'),
(7, 'program', 'close'),
(7, 'program', 'create'),
(7, 'program', 'delete'),
(7, 'program', 'edit'),
(7, 'program', 'finish'),
(7, 'program', 'index'),
(7, 'program', 'manageMembers'),
(7, 'program', 'setPlanduration'),
(7, 'program', 'start'),
(7, 'program', 'suspend'),
(7, 'program', 'transfer'),
(8, 'my', 'program'),
(8, 'program', 'activate'),
(8, 'program', 'close'),
(8, 'program', 'delete'),
(8, 'program', 'finish'),
(8, 'program', 'index'),
(8, 'program', 'manageMembers'),
(8, 'program', 'setPlanduration'),
(8, 'program', 'start'),
(8, 'program', 'suspend'),
(8, 'program', 'transfer'),
(9, 'my', 'program'),
(9, 'program', 'activate'),
(9, 'program', 'close'),
(9, 'program', 'create'),
(9, 'program', 'delete'),
(9, 'program', 'edit'),
(9, 'program', 'finish'),
(9, 'program', 'index'),
(9, 'program', 'manageMembers'),
(9, 'program', 'setPlanduration'),
(9, 'program', 'start'),
(9, 'program', 'suspend'),
(9, 'program', 'transfer'),
(10, 'my', 'program'),
(10, 'program', 'activate'),
(10, 'program', 'close'),
(10, 'program', 'create'),
(10, 'program', 'delete'),
(10, 'program', 'edit'),
(10, 'program', 'finish'),
(10, 'program', 'index'),
(10, 'program', 'start'),
(10, 'program', 'suspend'),
(11, 'program', 'activate'),
(11, 'program', 'close'),
(11, 'program', 'create'),
(11, 'program', 'delete'),
(11, 'program', 'edit'),
(11, 'program', 'finish'),
(11, 'program', 'index'),
(11, 'program', 'start'),
(11, 'program', 'suspend'),
(12, 'program', 'activate'),
(12, 'program', 'close'),
(12, 'program', 'create'),
(12, 'program', 'delete'),
(12, 'program', 'edit'),
(12, 'program', 'finish'),
(12, 'program', 'index'),
(12, 'program', 'start'),
(12, 'program', 'suspend');
