ALTER TABLE `zt_extension` DROP INDEX `name`;
ALTER TABLE `zt_extension` DROP INDEX `addedTime`;
ALTER TABLE `zt_extension` ADD INDEX `extension` (`name`, `installedTime`);
ALTER TABLE `zt_file` DROP INDEX `objectType`;
ALTER TABLE `zt_file` DROP INDEX `objectID`;
ALTER TABLE `zt_file` ADD INDEX `file` (`objectType`, `objectID`);
ALTER TABLE `zt_module` DROP INDEX `root`;
ALTER TABLE `zt_module` DROP INDEX `type`;
ALTER TABLE `zt_module` ADD INDEX `module` (`root`, `type`, `path`);
ALTER TABLE `zt_project` DROP INDEX `project`;
ALTER TABLE `zt_project` ADD INDEX `project` (`parent`, `begin`, `end`, `status`, `order`);
ALTER TABLE `zt_story` DROP INDEX `status`;
ALTER TABLE `zt_story` DROP INDEX `product`;
ALTER TABLE `zt_story` ADD INDEX `story` (`product`, `module`, `status`, `assignedTo`);
ALTER TABLE `zt_task` DROP INDEX `project`;;
ALTER TABLE `zt_task` DROP INDEX `type`;
ALTER TABLE `zt_task` DROP INDEX `status`;
ALTER TABLE `zt_task` ADD INDEX `task` (`project`, `module`, `story`, `assignedTo`);
ALTER TABLE `zt_testresult` DROP INDEX `run`;
ALTER TABLE `zt_testresult` DROP INDEX `case`;
ALTER TABLE `zt_testresult` ADD INDEX `testresult` (`case`, `version`, `run`);
ALTER TABLE `zt_todo` DROP INDEX `user`;
ALTER TABLE `zt_todo` ADD INDEX `todo` (`account`, `date`);
ALTER TABLE `zt_user` DROP INDEX `dept`;
ALTER TABLE `zt_user` ADD INDEX `user` (`dept`, `email`, `commiter`);
ALTER TABLE `zt_userquery` DROP INDEX `account`;
ALTER TABLE `zt_userquery` DROP INDEX `module`;
ALTER TABLE `zt_userquery` ADD INDEX `query` (`account`, `module`);
