ALTER TABLE `zt_api` MODIFY COLUMN `desc` mediumtext NULL;
ALTER TABLE `zt_apispec` MODIFY COLUMN `desc` mediumtext NULL;
ALTER TABLE `zt_apistruct` MODIFY COLUMN `desc` mediumtext NOT NULL DEFAULT '';
ALTER TABLE `zt_bug` MODIFY COLUMN `steps` mediumtext NOT NULL;
ALTER TABLE `zt_build` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_design` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_designspec` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_doclib` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_entry` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_extension` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_holiday` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_kanbanspace` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_kanban` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_kanbancard` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_product` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_productplan` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_project` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_release` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_storyspec` MODIFY COLUMN `spec` mediumtext NOT NULL;
ALTER TABLE `zt_storyspec` MODIFY COLUMN `verify` mediumtext NOT NULL;
ALTER TABLE `zt_task` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_testsuite` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_testtask` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_todo` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_service` MODIFY COLUMN `desc` mediumtext;
ALTER TABLE `zt_deploy` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_traincourse` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_activity` MODIFY COLUMN `content` mediumtext NOT NULL;
ALTER TABLE `zt_nc` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_zoutput` MODIFY COLUMN `content` mediumtext NOT NULL;
ALTER TABLE `zt_process` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_budget` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_researchplan` MODIFY COLUMN `outline` mediumtext NOT NULL;
ALTER TABLE `zt_researchplan` MODIFY COLUMN `schedule` mediumtext NOT NULL;
ALTER TABLE `zt_researchreport` MODIFY COLUMN `content` mediumtext NOT NULL;
ALTER TABLE `zt_assetlib` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_meastemplate` MODIFY COLUMN `content` mediumtext NOT NULL;
ALTER TABLE `zt_issue` MODIFY COLUMN `desc` mediumtext NOT NULL;
ALTER TABLE `zt_risk` MODIFY COLUMN `prevention` mediumtext NOT NULL;
ALTER TABLE `zt_risk` MODIFY COLUMN `remedy` mediumtext NOT NULL;
ALTER TABLE `zt_risk` MODIFY COLUMN `resolution` mediumtext NOT NULL;
ALTER TABLE `zt_opportunity` MODIFY COLUMN `prevention` mediumtext NOT NULL;
ALTER TABLE `zt_opportunity` MODIFY COLUMN `resolution` mediumtext NOT NULL;
ALTER TABLE `zt_trainplan` MODIFY COLUMN `summary` mediumtext NOT NULL;
ALTER TABLE `zt_gapanalysis` MODIFY COLUMN `analysis` mediumtext NOT NULL;

ALTER TABLE `zt_file` MODIFY COLUMN `title` varchar(255) NOT NULL;
