#!/usr/bin/env php
<?php
include dirname(__FILE__, 5) . "/test/lib/init.php";
include dirname(__FILE__, 2) . '/task.class.php';

/**

title=taskModel->manageTaskTeamMember();
cid=1
pid=1

*/

$modeList         = array('linear', 'multi');
$taskIdList       = array(1, 2, 3);
$taskStatusList   = array('wait', 'doing', 'done');
$row              = array(0, 1, 2, 3, 4, 5);
$account          = array('admin', 'user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user9');
$minStatus        = array('done', 'doing', 'wait');
$undoneUsersList  = array(array('admin' => 'admin', 'user1' => 'user1', 'user2' => 'user2', 'user3' => 'user3'), array('user4' => 'user4', 'user5' => 'user5', 'user6' => 'user6', 'user7' => 'user7', 'user8' => 'user8'), array());
$teamSourceList   = array(array('admin', 'user1', 'user2', 'user3'), array('admin', 'user1', 'user2', 'user4'), array('user4', 'user5', 'user6', 'user7', 'user9'), array('user4', 'user5', 'user6', 'user7', 'user8'));
$teamEstimateList = array(array(1, 2, 3, 4), array(2, 3, 4, 5, 7));
$teamConsumedList = array(array(4, 3, 2, 1), array(4, 3, 2, 1, 0));
$teamLeftList     = array(array(0, 0, 0, 0), array(0, 1, 3, 5, 7));
$inTeams          = array(true, false);

$task = new taskTest();

r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 admin 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[0], $row[5], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 admin 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 admin 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[0], $row[5], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 admin 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的串行多人任务内用户 admin 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[0], $row[5], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的串行多人任务内用户 admin 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[0], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的串行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 admin 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[1], $row[5], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 admin 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[0], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 admin 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[1], $row[5], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 admin 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[1], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的并行多人任务内用户 admin 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[1], $row[5], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的并行多人任务内用户 admin 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[0], $taskStatusList[2], $modeList[1], $row[0], $account[0], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 1 任务状态为 done 最小任务状态为done 的并行多人任务内用户 admin 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息


r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 user6 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[0], $row[5], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 user6 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 user6 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[0], $row[5], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 user6 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的串行多人任务内用户 user6 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[0], $row[5], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的串行多人任务内用户 user6 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[0], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的串行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 user6 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[1], $row[5], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 user6 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[0], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 wait 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 user6 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[1], $row[5], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 user6 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[1], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 doing 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息

r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的并行多人任务内用户 user6 不存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[1], $row[5], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], false, false, $inTeams[0]))                           && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的并行多人任务内用户 user6 不存在期望 消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[0])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[0], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在用户列表中的成员信息
r($task->manageTaskTeamMemberTest($taskIdList[1], $taskStatusList[2], $modeList[1], $row[0], $account[6], $minStatus[0], $undoneUsersList[2], $teamSourceList[0], $teamEstimateList[0], $teamConsumedList[0], $teamLeftList[0], $inTeams[1])) && p('minStatus,memberData') && e('');  // 测试更新任务ID 2 任务状态为 done 最小任务状态为done 的并行多人任务内用户 user6 存在消耗和剩余的 不在未完成任务列表 不在用户列表中的成员信息
