window.initUserSelector = function($element)
{
    const $root = $($element);
    if(!$root.length || $root.data('user-selector-initialized')) return;
    $root.data('user-selector-initialized', true);

    /* 从根节点读取最终提交字段名，和 PHP 侧隐藏输入保持一致。
       Read the effective submit field name from the root node so JS stays aligned
       with the hidden inputs generated by PHP. */
    const widgetName = $root.data('name') || 'selectedUsers[]';

    /* 统一用字符串比较账号，避免 null / number / string 混用造成匹配失败。
       Normalize account comparison to strings to avoid mismatches caused by mixed
       null / number / string values. */
    const normalizeAccount = account => `${account ?? ''}`;
    const getCheckbox = account => $root.find('.user-selector-user-checkbox').filter(function()
    {
        return normalizeAccount(this.value) === normalizeAccount(account);
    }).first();
    const getUserItem = account => getCheckbox(account).closest('[data-user]');
    const getSearchInput = () => $root.find('[data-search="true"]');
    const getSearchClear = () => $root.find('[data-clear-search="true"]');
    const getVisibleItems = () => $root.find('[data-user]').filter(function()
    {
        return $(this).css('display') !== 'none';
    });

    const selectedAccounts = () =>
    {
        return $root.find('.user-selector-user-checkbox:checked').map((_i, checkbox) => checkbox.value).get();
    };

    /* 部门只允许一个激活项，筛选时以当前激活部门为准。
       Only one department stays active at a time, and filtering always follows
       the currently active department. */
    const updateDeptActive = dept =>
    {
        $root.find('.user-selector-dept-option').removeClass('is-active');
        $root.find(`[data-dept="${dept}"]`).addClass('is-active');
    };

    /* 隐藏输入是表单提交的真实数据源，界面上的“已选择”列表只是展示层。
       Hidden inputs are the actual form-submission source, while the selected
       list on the right is presentation only. */
    const renderHiddenInputs = accounts =>
    {
        const $container = $root.find('[data-hidden-inputs="true"]');
        $container.empty();
        accounts.forEach(account =>
        {
            $('<input>')
                .attr('type', 'hidden')
                .attr('name', widgetName)
                .attr('value', account)
                .attr('data-hidden-input', 'true')
                .appendTo($container);
        });
    };

    /* 右侧已选择列表完全由当前勾选状态重新渲染，避免增量操作导致状态漂移。
       Re-render the selected list from the current checked state each time to
       avoid drift caused by incremental DOM mutations. */
    const renderSelectedList = accounts =>
    {
        const $list = $root.find('[data-selected-list="true"]');
        $list.empty();

        accounts.forEach(account =>
        {
            const $user = getUserItem(account);
            if(!$user.length) return;

            const name = $user.find('.user-selector-user-name').text();
            const avatarNode = $user.find('.user-selector-avatar')[0];
            const avatarHTML = avatarNode ? avatarNode.outerHTML : '';

            const $item = $(`
                <li class="user-selector-selected-item" data-selected-user="${account}">
                    ${avatarHTML}
                    <span class="user-selector-selected-name"></span>
                    <button type="button" class="user-selector-remove user-selector-remove-user" data-remove-user="${account}"></button>
                </li>
            `);

            $item.find('.user-selector-selected-name').text(name);
            $item.find('.user-selector-remove').append('<i class="icon icon-close"></i>');
            $list.append($item);
        });

        $root.find('[data-selected-count="true"]').text(`(${accounts.length})`);
    };

    /* 同步三个界面层级：
       1. 可选列表勾选态
       2. 已选择列表
       3. 隐藏表单输入
       Synchronize three UI layers:
       1. visual checked state in the selectable list
       2. selected list on the right
       3. hidden form inputs */
    const syncState = () =>
    {
        $root.find('[data-user]').each((_i, item) =>
        {
            const $item = $(item);
            const checked = $item.find('.user-selector-user-checkbox').prop('checked');
            $item.find('.user-selector-user-indicator').toggleClass('is-checked', checked);
        });

        const accounts = selectedAccounts();
        renderSelectedList(accounts);
        renderHiddenInputs(accounts);
    };

    /* 过滤逻辑同时受“部门”和“关键词”两层条件控制。
       Filtering is controlled by both the active department and the keyword. */
    const filterUsers = () =>
    {
        const activeDept = $root.find('.user-selector-dept-option.is-active').data('dept');
        const keyword    = ((getSearchInput().val() || '') + '').trim().toLowerCase();
        let visibleCount = 0;

        $root.find('[data-user]').each((_i, item) =>
        {
            const $item    = $(item);
            const path     = ($item.data('path') || '') + '';
            const keywords = (($item.data('keywords') || '') + '').toLowerCase();

            const deptMatch = activeDept === 'all' || activeDept === undefined ? true : path.indexOf(`,${activeDept},`) >= 0;
            const textMatch = !keyword || keywords.indexOf(keyword) >= 0;
            const visible   = deptMatch && textMatch;

            $item.toggle(visible);
            if(visible) visibleCount++;
        });

        $root.find('[data-empty="true"]').toggleClass('hidden', visibleCount > 0);
        getSearchClear().toggleClass('hidden', keyword.length === 0);
    };

    /* 部门树交互。
       Department tree interactions. */
    $root.on('click', '.user-selector-dept-toggle', function(event)
    {
        event.preventDefault();
        event.stopPropagation();

        const $node  = $(this).closest('[data-dept-node]');
        if(!$node.length) return;
        const expanded = $node.attr('data-expanded') === 'true';
        $node.attr('data-expanded', expanded ? 'false' : 'true');
    });

    $root.on('click', '.user-selector-dept-option', function(event)
    {
        event.preventDefault();
        updateDeptActive($(this).data('dept'));
        filterUsers();
    });

    /* 搜索框交互。
       Search-box interactions. */
    $root.on('input', '[data-search="true"]', function()
    {
        filterUsers();
    });

    $root.on('click', '[data-clear-search="true"]', function(event)
    {
        event.preventDefault();
        event.stopPropagation();

        const $input = getSearchInput();
        $input.val('').trigger('input').trigger('focus');
    });

    /* 用户勾选交互。
       User selection interactions. */
    $root.on('click', '.user-selector-user-btn', function(event)
    {
        event.preventDefault();
        if($(event.target).closest('.user-selector-user-checkbox').length) return;

        const $checkbox = $(this).find('.user-selector-user-checkbox');
        $checkbox.prop('checked', !$checkbox.prop('checked')).trigger('change');
    });

    $root.on('change', '.user-selector-user-checkbox', function()
    {
        syncState();
    });

    /* 右侧移除操作需要回写左侧勾选框，保证两侧状态来源一致。
       Removing a user from the right-side list must also uncheck the source
       checkbox on the left so both panes stay consistent. */
    $root.on('click', '.user-selector-remove-user', function(event)
    {
        event.preventDefault();
        event.stopPropagation();

        const account = normalizeAccount($(this).closest('[data-selected-user]').attr('data-selected-user') || $(this).attr('data-remove-user'));
        if(!account) return;

        const $checkbox = getCheckbox(account);
        if(!$checkbox.length) return;

        $(this).closest('[data-selected-user]').remove();
        $checkbox.prop('checked', false).trigger('change');
    });

    /* 批量操作只作用于当前可见用户，和搜索/部门筛选保持一致。
       Batch actions only affect currently visible users so they stay aligned
       with search and department filtering. */
    $root.on('click', '.user-selector-action-select-all', function(event)
    {
        event.preventDefault();
        event.stopPropagation();
        getVisibleItems().find('.user-selector-user-checkbox').prop('checked', true);
        syncState();
    });

    $root.on('click', '.user-selector-action-inverse', function(event)
    {
        event.preventDefault();
        event.stopPropagation();
        getVisibleItems().each((_i, item) =>
        {
            const $checkbox = $(item).find('.user-selector-user-checkbox');
            $checkbox.prop('checked', !$checkbox.prop('checked'));
        });
        syncState();
    });

    /* 初始化时先对现有默认值做一次完整同步。
       Run a full synchronization once on init to reflect preselected values. */
    syncState();
    filterUsers();
};
