<?php
global $lang;
$config->bug->search['module']                   = 'bug';
$config->bug->search['fields']['id']             = $lang->bug->id;
$config->bug->search['fields']['title']          = $lang->bug->title;
$config->bug->search['fields']['steps']          = $lang->bug->steps;
$config->bug->search['fields']['assignedTo']     = $lang->bug->assignedTo;
$config->bug->search['fields']['resolvedBy']     = $lang->bug->resolvedBy;
$config->bug->search['fields']['openedBy']       = $lang->bug->openedBy;
$config->bug->search['fields']['project']        = $lang->bug->project;
$config->bug->search['fields']['closedBy']       = $lang->bug->closedBy;
$config->bug->search['fields']['lastEditedBy']   = $lang->bug->lastEditedBy;
$config->bug->search['fields']['status']         = $lang->bug->status;
$config->bug->search['fields']['severity']       = $lang->bug->severity;
$config->bug->search['fields']['type']           = $lang->bug->type;
$config->bug->search['fields']['os']             = $lang->bug->os;
$config->bug->search['fields']['browser']        = $lang->bug->browser;
$config->bug->search['fields']['resolution']     = $lang->bug->resolution;
$config->bug->search['fields']['mailto']         = $lang->bug->mailto;
$config->bug->search['fields']['openedDate']     = $lang->bug->openedDate;
$config->bug->search['fields']['assignedDate']   = $lang->bug->assignedDate;
$config->bug->search['fields']['closedDate']     = $lang->bug->closedDate;
$config->bug->search['fields']['lastEditedDate'] = $lang->bug->lastEditedDate;

$config->bug->search['params']['title']        = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->bug->search['params']['steps']        = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->bug->search['params']['project']      = array('operator' => '=',       'control' => 'select', 'values' => 'projects');
$config->bug->search['params']['assignedTo']   = array('operator' => '=',       'control' => 'select', 'values' => 'users');
$config->bug->search['params']['resolvedBy']   = array('operator' => '=',       'control' => 'select', 'values' => 'users');
$config->bug->search['params']['openedBy']     = array('operator' => '=',       'control' => 'select', 'values' => 'users');
$config->bug->search['params']['closedBy']     = array('operator' => '=',       'control' => 'select', 'values' => 'users');
$config->bug->search['params']['lastEditedBy'] = array('operator' => '=',       'control' => 'select', 'values' => 'users');
$config->bug->search['params']['status']       = array('operator' => '=',       'control' => 'select', 'values' => $lang->bug->statusList);
$config->bug->search['params']['severity']     = array('operator' => '=',       'control' => 'select', 'values' => $lang->bug->severityList);
$config->bug->search['params']['type']         = array('operator' => '=',       'control' => 'select', 'values' => $lang->bug->typeList);
$config->bug->search['params']['os']           = array('operator' => '=',       'control' => 'select', 'values' => $lang->bug->osList);
$config->bug->search['params']['browser']      = array('operator' => '=',       'control' => 'select', 'values' => $lang->bug->browserList);
$config->bug->search['params']['resolution']   = array('operator' => '=',       'control' => 'select', 'values' => $lang->bug->resolutionList);
$config->bug->search['params']['mailto']       = array('operator' => 'include', 'control' => 'select', 'values' => 'users');
