<?php
global $lang;
$config->product->form = new stdclass();
$config->product->form->create = array();
$config->product->form->create['program']   = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->product->form->create['line']      = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->product->form->create['lineName']  = array('type' => 'string',  'control' => 'input',        'required' => false, 'default' => '', 'filter' => 'trim');
$config->product->form->create['name']      = array('type' => 'string',  'control' => 'input',        'required' => true,  'default' => '', 'filter' => 'trim');
$config->product->form->create['code']      = array('type' => 'string',  'control' => 'input',        'required' => true,  'default' => '', 'filter' => 'trim');
$config->product->form->create['PO']        = array('type' => 'account', 'control' => 'select',       'required' => false, 'default' => '', 'options' => array());
$config->product->form->create['QD']        = array('type' => 'account', 'control' => 'select',       'required' => false, 'default' => '', 'options' => array());
$config->product->form->create['RD']        = array('type' => 'account', 'control' => 'select',       'required' => false, 'default' => '', 'options' => array());
$config->product->form->create['reviewer']  = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'filter' => 'join', 'options' => 'users');
$config->product->form->create['type']      = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => 'normal', 'options' => $lang->product->typeList);
$config->product->form->create['status']    = array('type' => 'string',  'control' => 'hidden',       'required' => false, 'default' => 'normal');
$config->product->form->create['desc']      = array('type' => 'string',  'control' => 'textarea',     'required' => false, 'default' => '');
$config->product->form->create['acl']       = array('type' => 'string',  'control' => 'radio',        'required' => false, 'default' => 'private', 'options' => $lang->product->aclList);
$config->product->form->create['whitelist'] = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'filter' => 'join', 'options' => 'users');

$config->product->form->edit = array();
$config->product->form->edit['program']        = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->product->form->edit['line']           = array('type' => 'int',     'control' => 'select',       'required' => false, 'default' => 0,  'options' => array());
$config->product->form->edit['name']           = array('type' => 'string',  'control' => 'input',        'required' => true,  'default' => '', 'filter' => 'trim');
$config->product->form->edit['code']           = array('type' => 'string',  'control' => 'input',        'required' => true,  'default' => '', 'filter' => 'trim');
$config->product->form->edit['PO']             = array('type' => 'account', 'control' => 'select',       'required' => false, 'default' => '', 'options' => array());
$config->product->form->edit['QD']             = array('type' => 'account', 'control' => 'select',       'required' => false, 'default' => '', 'options' => array());
$config->product->form->edit['RD']             = array('type' => 'account', 'control' => 'select',       'required' => false, 'default' => '', 'options' => array());
$config->product->form->edit['reviewer']       = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'filter' => 'join', 'options' => 'users');
$config->product->form->edit['type']           = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => 'normal', 'options' => $lang->product->typeList);
$config->product->form->edit['status']         = array('type' => 'string',  'control' => 'select',       'required' => false, 'default' => 'normal', 'options' => $lang->product->statusList);
$config->product->form->edit['desc']           = array('type' => 'string',  'control' => 'textarea',     'required' => false, 'default' => '');
$config->product->form->edit['acl']            = array('type' => 'string',  'control' => 'radio',        'required' => false, 'default' => 'private', 'options' => $lang->product->aclList);
$config->product->form->edit['whitelist']      = array('type' => 'array',   'control' => 'multi-select', 'required' => false, 'default' => '', 'filter' => 'join', 'options' => 'users');
$config->product->form->edit['changeProjects'] = array('type' => 'string',  'control' => 'hidden',       'required' => false, 'default' => '');
