FROM hub.qucheng.com/ci/zentao-ztf

# Install zentao
ARG VERSION
ENV ZENTAO_VER=${VERSION}
ENV EASYSOFT_APP_NAME="ZenTao $ZENTAO_VER"

ENV MYSQL_INTERNAL="true"

# Copy ZenTao
COPY --chown=nobody:nogroup . /apps/zentao/
RUN mkdir /apps/zentao/tmp && chmod 777 /apps/zentao/tmp
